  const tabs = [
    { key: 'hero', label: 'Hero Banner', icon: Image },
    { key: 'homepage_sections', label: 'Homepage', icon: Monitor },
    { key: 'page_headers', label: 'Page Headers', icon: Monitor },
    { key: 'programs', label: 'Programs', icon: Package, count: programs.length },
    { key: 'pricing_hub', label: 'Pricing Hub', icon: DollarSign },
    { key: 'upcoming_hub', label: 'Upcoming Hub', icon: Calendar },
    { key: 'upcoming_card_quotes', label: 'Upcoming Card Quotes', icon: Calendar },
    { key: 'sessions', label: 'Sessions', icon: Calendar, count: sessions.length },
    { key: 'testimonials', label: 'Testimonials', icon: MessageSquare, count: testimonials.length },
    { key: 'text_testimonials', label: 'Text Quotes', icon: Quote },
    { key: 'stats', label: 'Stats', icon: BarChart3, count: stats.length },
    { key: 'header_footer', label: 'Header & Footer', icon: Globe },
    { key: 'enrollments', label: 'Enrollments', icon: Users },
    { key: 'inbox', label: 'Inbox', icon: Inbox },
    { key: 'clients', label: 'Iris Garden', icon: Users },
    { key: 'promotions', label: 'Promotions', icon: Gift },
    { key: 'discounts', label: 'Discounts & Loyalty', icon: Tag },
    { key: 'exchange_rates', label: 'Exchange Rates', icon: Globe },
    { key: 'subscribers', label: 'Subscribers', icon: Mail, count: subscribers.length },
    { key: 'styles', label: 'Global Styles', icon: Palette },
    { key: 'payment_settings', label: 'Payments', icon: Tag },
    { key: 'india_payments', label: 'India Proofs', icon: Tag },
    { key: 'fraud_alerts', label: 'Fraud Detection', icon: ShieldAlert },
    { key: 'receipt_template', label: 'Receipt Template', icon: FileText },
    { key: 'api_keys', label: 'API Keys', icon: Settings },
    // Dashboard Tabs separated at bottom
    { key: 'dashboard_settings', label: 'Dashboard Settings', icon: Layout },
    { key: 'sanctuary_settings', label: 'Sanctuary Design', icon: Image },
  ];